### ISSUE TITLE
DeskClock 

### ISSUE THREAD

**Issue by mclaude74** [ingbrzy/MA-XML-11-RUSSIAN#1]
@ingbrzy 

https://github.com/ingbrzy/Xiaomi.eu-MIUIv11-XML-Compare/blob/4428ace319887200a04df2b50361795ae034a4ad/nitrogen/DeskClock.apk/res/values/strings.xml#L227

https://github.com/ingbrzy/MA-XML-11-RUSSIAN/blob/93553554d0e624fbbe1c9542d0436219df164823/Russian/main/DeskClock.apk/res/values-ru/strings.xml#L178

On Russian and others langs, except English, we have bug, see screenshots.

![Screenshot_2019-09-28-02-43-03-504_com android deskclock](https://user-images.githubusercontent.com/45774262/65808130-17fabe80-e19b-11e9-824c-953ab1e28a21.jpg)
![Screenshot_2019-09-28-02-47-28-666_com android deskclock](https://user-images.githubusercontent.com/45774262/65808131-17fabe80-e19b-11e9-8111-09184fb13239.jpg)

**Comment by ingbrzy** [comment]
HTML tags are not supported by apktool...
