### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by mclaude74** [ingbrzy/MA-XML-11-RUSSIAN#13]
Hi,  @ingbrzy 
Why is the translation of these lines not added to assemblies?
This has been going on for a long time.

![image](https://user-images.githubusercontent.com/45774262/72906917-0938a880-3d44-11ea-872b-b87a6fb239b6.png)

https://github.com/ingbrzy/MA-XML-11-RUSSIAN/blob/61d5e57c4384bfe9057cfcb783372620e8e9d74f/Russian/main/Settings.apk/res/values-ru/arrays.xml#L1299-L1322

**Comment by ingbrzy** [comment]
its specific array for each device.. so to avoid FC of dev settings, its not included in the translations.. in the dev settings are supposed to play only developers.. and who does not speak English, is not a dev..
