### ISSUE TITLE
Null in strings

### ISSUE THREAD

**Issue by mclaude74** [ingbrzy/MA-XML-11-RUSSIAN#14]
Hi, @ingbrzy 
Why is the application name incorrect?

https://github.com/ingbrzy/MA-XML-11-RUSSIAN/blob/f9f5895d6928ad1ca6f92b20cf07a15c1448ecc0/Russian/main/Settings.apk/res/values-ru/strings.xml#L3834-L3837

![image](https://user-images.githubusercontent.com/45774262/72989905-3b0f4500-3e00-11ea-8103-dc6a965e034c.png)

**Comment by ingbrzy** [comment]
not a translation issue..
