### ISSUE TITLE
Безграничный экран

### ISSUE THREAD

**Issue by bagdasarov** [ingbrzy/MA-XML-11-RUSSIAN#16]
20.1.21 - Mix 3 / Mix 2s / Mi Note 10

**Безграничный экран** (нижняя строка меню) почему-то переименовали в 'Полноэкранный режим'. И теперь в меню два совершенно разных полноэкранных режима. Это дико путает. Верните pls **Безграничный экран** или обзовите как-то иначе. Но чтобы не было путаницы!

![IMG_20200205_101431](https://user-images.githubusercontent.com/48652324/73823428-dfca5300-4800-11ea-9842-9eb7421230d1.jpg)

**Comment by mclaude74** [comment]
@bagdasarov 
"Полноэкранный режим" в нижней строке переименован в "Полноэкранная навигация". 
https://github.com/ingbrzy/MA-XML-11-RUSSIAN/commit/300458561edee0bc24861f6f406218b341aa5f30#diff-9a9a556adf725bcbd918c40e8b7eda36

Должно попасть в следующую сборку.
Тикет закрываем?

**Comment by bagdasarov** [comment]
Закрываем, конечно.
Это просто был репорт / сигнал.
Спасибо, что реагируете.

- 
С уважением,
Илья Багдасаров
Tel. 	+373 /79/ 888899
Skype  ilia.bagdasarov
linkedin.com/in/bagdasarov <http://www.linkedin.com/in/bagdasarov>_________________________________________
This e-mail originates from  <mailto:%C2%A0ilia.bagdasarov@gmail.com>ilia.bagdasarov@gmail.com <mailto:ilia.bagdasarov@gmail.com>
‌‌
‌‌
‌‌

‌‌
