### ISSUE TITLE
Перевод

### ISSUE THREAD

**Issue by Glocksss** [ingbrzy/MA-XML-11-RUSSIAN#3]
Привет,абиентный дисплей можно исправить...как то бэ звучит.
В нем же side panel chortcust
В нем же - отображение элементов -turn off when.......
Настройки - privacy
Камера - настройки - watermark, correct face....,poup-upcamera

**Comment by mclaude74** [comment]
Привет, какой вариант перевода для "амбиентный дисплей" можешь предложить?
Эти пункты видны только для телефонов с AMOLED-матрицей, у меня же IPS.
У Miroom переведено как:  Режим "Always on Display"

Сейчас очень много изменений: 127 files Showing  with 5,847 additions and 3,187 deletions.
Зашиваюсь, т.к. один тяну это дело, в свободное личное время.

**Comment by induction-lab** [comment]
Привет. Могу присоединиться к переводу если покажете на примере как можно помочь.

**Comment by mclaude74** [comment]
@induction-lab, привет.

Не знаю, есть ли у вас опыт работы с github  и опыт перевода. 
Лично я все осваивал с нуля, смотрел инструкции в инете. Образования переводчика нет, но как программист более-менее владею английским на уровне чтения технической документации со словарем, плюс набил руку за год доперевода.

Репозиторий перевода на русский язык на xiaomi.eu для все устройств один:
https://github.com/ingbrzy/MA-XML-11-RUSSIAN
Как для еженедельных, так и для стабильных сборок.

1. Нужно зарегистрироваться на github.com, затем сделать форк (другими словами - локальную копию) репозитория MA-XML-11-RUSSIAN. 
Я использую GitHub Desktop, но можно и через браузер (но там легко потерять правки в случае сбоя или ошибочного действия). 

2. Все изменения выкладываются в
https://github.com/ingbrzy/Xiaomi.eu-MIUIv11-XML-Compare 

Обычно отслеживаю в браузере репозиторий для устройства dipper, т.к. для него выкладывают изменения в ресурсах до выхода очередной прошивки и можно успеть сделать доперевод в опережающем режиме, до выхода сборки.
Для остальных устройств изменения - после выхода. По большей части, содержимое репозиториев для каждого устройства одинаковое, но для устройств на Android 9 и Android 10 есть различия (при сборке для конкретных устройств подтягиваются только нужные ресурсы).

Пример: 
Идем в ветку 
https://github.com/ingbrzy/Xiaomi.eu-MIUIv11-XML-Compare/tree/master/dipper

Нажимаем на странице репозитория кнопку History, получаем список изменений.
В списке нажимаем на HEX-ссылку вида "13d7b4b"

https://github.com/ingbrzy/Xiaomi.eu-MIUIv11-XML-Compare/commit/13d7b4b0aee351ccd876c7edcf43a77e02107b8c#diff-6d31a14788996ac7c0765acc40d0ba21

Видим список добавленных (зеленым) и удаленных (красным) строк, или измененных строк.
Сверяемся с нашим репозиторием, добавляем перевод, удаляем устаревшие строки.

Например:
Для ресурса dipper/AuthManager.apk/res/values/strings.xml видим

--  &lt;string name="never_ask_again"&gt;"Don't ask again"&lt;/string&gt;
++ &lt;string name="never_ask_again"&gt;"Don't ask again after restricting"&lt;/string&gt;
Смотрим соответствующий ресурс в репозитории русского перевода: 
https://github.com/ingbrzy/MA-XML-11-RUSSIAN/blob/master/Russian/main/AuthManager.apk/res/values-ru/strings.xml

По тегу never_ask_again видим:
&lt;string name="never_ask_again"&gt;Больше не спрашивать&lt;/string&gt;
Можем изменить перевод на 
&lt;string name="never_ask_again"&gt;Больше не спрашивать после ограничения&lt;/string&gt;
Но в конкретно в этом случае нет смысла удлинять перевод.

После изменений делаем commit (фиксацию) и pull (запрос на слияние). 
Если изменения корректные, я или ingbrzy (лидер проекта xiaomi.eu) подтвердим слияние правок.

Я стараюсь делать лаконичный перевод, т.к. интерфейс MIUI больше рассчитан на китайские иероглифы, которые обычно короткие, а английский перевод с китайского слишком длинный и "вежливый", и часто переведенные строки не вписываются в экран или элемент управления. 

Также стараюсь придерживаться единой стилистики перевода, для этого делаю поиск по репозиторию в поисках похожих строк. Например, незачем переводить "screenshot" как "cнимок экрана", когда в других приложениях или других строках этого же файла в переводе используется "скриншот".

Также стоит предварительно делать поиск по тегу по всему репозиторию, т.к.
некоторые строки могут быть уже переведены в других приложениях. 

Если на устройстве во время пользования найдена непереведенная строка, можно сделать скриншот, затем поискать в Xiaomi.eu-MIUIv11-XML-Compare совпадения по этой строке, после этого проверить наличие найденного тега в соответствующем файле в MA-XML-11-RUSSIAN.

Буду рад, если получится разобраться во всем этом механизме и помогать с допереводом.
