### ISSUE TITLE
Всплывающее окно о защите приложений на английском

### ISSUE THREAD

**Issue by Glocksss** [ingbrzy/MA-XML-11-RUSSIAN#5]
Я понимаю , что это все на уровне энтузиазма, и большое спасибо за перевод,но хотелось бы идеала.

**Comment by mclaude74** [comment]
Прикладывайте скриншоты, так проще будет определить место недоперевода (в именах скриншотов содержится имя приложения)

**Comment by mclaude74** [comment]
Доперевод добавлен:
https://github.com/ingbrzy/MA-XML-11-RUSSIAN/blob/de66eba75f1306d2bf9b98f55c9c78ab66f7db97/Russian/main/SecurityCenter.apk/res/values-ru/strings.xml#L35-L38
